---
- name: Get latest Ubuntu changes
  apt: upgrade=dist update_cache=yes

- name: Check if a reboot is required
  register: file
  stat: path=/var/run/reboot-required get_md5=no

- name: Schedule a reboot
  command: "/sbin/shutdown -r 04:00"
  when: file.stat.exists == true
 

