---
- name: Global Playbook 
  hosts: all
  sudo: true
  roles:
    - role.ubuntu-updates
    - role.ntp
- name: Docker Playbook 
  hosts: docker
  sudo: true
  roles:
    - role.docker
- name: VM Docker1 Playbook 
  hosts: docker1
  sudo: true
  tasks:
  - name: RabbitMQ
    docker:
      name: rabbitmq
      image: rabbitmq:management
      state: reloaded
      docker_api_version: 1.18
      ports:
      - "15672:15672"
  - name: chatter
    docker:
      name: chatter
      image: rjordan/chatter:1.1
      state: reloaded
      docker_api_version: 1.18
      links:
      - "rabbitmq"
      ports:
      - "3000:3000"
      - "3001:3001"
- name: Load Balancer Playbook 
  hosts: balancer
  sudo: true
  roles:
   - role: ansible-haproxy
     haproxy_version: 1.5
     haproxy_frontends:
     - name: 'http'
       ip: '*'
       port: "80"
       maxconn: '1000'
       default_backend: 'chatter'
       acl:
       - name: cws_acl
         condition: 'path_beg /ws'
       - name: rmq_acl
         condition: 'path_beg /mq'
       use_backend:
       - name: chatter_ws
         condition: 'if cws_acl'         
       - name: rabbitmq
         condition: 'if rmq_acl'         
     - name: 'httpws'
       ip: '*'
       port: "3001"
       maxconn: '1000'
       default_backend: 'chatter_ws'
     - name: 'rabbit'
       ip: '*'
       port: "15672"
       maxconn: '1000'
       default_backend: 'rabbitmq'
     haproxy_backends:
     - name: 'rabbitmq'
       servers:
         - name: 'docker1'
           ip: '10.20.1.3'
           port: "15672"
     - name: 'chatter'
       servers:
         - name: 'docker1'
           ip: '10.20.1.3'
           port: "3000"
     - name: 'chatter_ws'
       servers:
         - name: 'docker1'
           ip: '10.20.1.3'
           port: "3001"

  

